### ISSUE TITLE
.terminal class in CSS... what's the use case?

### ISSUE THREAD

**Issue by TheTourer** [jglovier/jekyll-new#2]
In this theme's main.css (lines 245-253), there is a section labeled "terminal" in the comments that is meant to style `<pre>` tags within a post, like so: 

``` css
/* terminal */
.post pre.terminal {
  border: 1px solid #000;
  background-color: #333;
  color: #FFF;
  border-radius: 3px;
}

.post pre.terminal code { background-color: #333; }
```

When applied (using Webkit's web inspector) to a `<pre>` tag generated by Jekyll's Syntax Highlighting, it creates a nice darkened effect for the preformatted text container. My question is, how does this class ever get used with the `{% highlight %}` tag in Jekyll? This needs to be added to a `<pre>` tag to achieve the desired affect, but `highlight` only accepts `cssclass` (takes a class for the enclosing `div`) or `prestyles` (takes inline styles for `pre`) as styling-related parameters relevant to this. Is there some other parameter to `{% highlight %}` that I am missing?

Thanks in advance!
