### ISSUE TITLE
Gists don't render properly

### ISSUE THREAD

**Issue by bricelam** [jglovier/jekyll-new#4]
![image](https://cloud.githubusercontent.com/assets/1226749/4210168/482bb8a2-3872-11e4-972b-adfbd49bfa1c.png)

**Comment by peterkos** [comment]
Since gists use `<pre>` & `<code>`, its styles are overridden by the jekyll theme's styling in the `css/main.css` file. 
Here are the lines that mess it up (229-251):

``` css
.post pre,
.post code {
  border: 1px solid #d5d5e9;
  background-color: #eef;
  padding: 8px 12px;
  border-radius: 3px;
  font-size: 15px;
}

.post code { padding: 1px 5px; }

.post ul,
.post ol { margin-left: 1.35em; }

.post pre code { border: none; }

/* terminal */
.post pre.terminal {
  border: 1px solid #000;
  background-color: #333;
  color: #FFF;
  border-radius: 3px;
}
```

Assigning a separate class/id for jekyll-generated `<pre>` & `<code>` elements might work, but for now, commenting out the lines above fixes it.
